// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cljnyelqcicgjxbfpwfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsam55ZWxxY2ljZ2p4YmZwd2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Mzc5MjgsImV4cCI6MjA2NjMxMzkyOH0.94qK_NgdwghGTkI8Ne3l_9MsW6j44FddcMhBF5j8n54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);